debug: True # To output global debug values
exp_name: name_not_specified # Used for saving partial outputs
preset_name: default

# Default values
proc_res: 6000
relative_scale: 10

# Required params
app:
  required_args: ['exp_name','img_overview', 'final_res']

# Parameters regarding homography estimation
homog:
  type: default
  feature_extractor: SuperPoint # Method to extract features
  max_feat_points: 16192 # Maximum feature points to find
  feature_matcher: LightGlue # Method to match features
  do_optimization: False # Turn optimization on
  max_matches: 200 # Max points to match
  optimizer: marek # Type of optimization

  # Preload saved homographies
  load:
  save:
  debug: True

# Parameters regarding optical flow estimation
optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960] # Size of input patches for model
  patch_overlap: [40,40] # Overlap of input patches
  # For image adjustment during calculation of optical flow
  adjust: False
  adjust_params:
    debug: False
    gaus_blur_sigma: 1.0
    subsample_factor: 2 # 1 / subsample_factor
  # Load saved flows
  load: # Path to FOLDER with saved flows
  save: # Path to FOLDER where save homogs if empty no save
  debug: True

light_optim:
  grid_size: 32
  use_tile: False
  tile_size: [2000,2000]
  loss_type: "mse"
  lr: 0.1
  steps: 50
  mode: [ "scale" ]
  optimizer: "LBFGS" # "adam" # LBFGS


# Parameters regarding stitching
stitcher:
  mode: actual
  blend_width: 100
  flow_margin: 50

hydra:
  run:
    chdir: false
