debug: False # To output global debug values
exp_name: name_not_specified # Used for saving partial outputs
preset_name: default

process_res: ??? # Processing resolution of image
final_res: ???  # Final resolution of image
input_folder: ??? # Path to the images
output_folder: ??? #
img_overview: ??? #

app:
  required_args: ['exp_name', 'input_folder', 'img_overview', 'output_folder', 'preset_name']

# Parameters regarding homography estimation
homog:
  type: default
  feature_extractor: SuperPoint # Method to extract features
  max_feat_points: 4096 # Maximum feature points to find
  feature_matcher: LightGlue # Method to match features
  do_optimization: False # Turn optimization on
  max_matches: 200 # Max points to match
  optimizer: marek # Type of optimization

  # Preload saved homographies
  load:
  save:
  debug: False

# Parameters regarding optical flow estimation
optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960] # Size of input patches for model
  patch_overlap: [40,40] # Overlap of input patches
  # For image adjustment during calculation of optical flow
  adjust: False
  adjust_params:
    debug: False
    gaus_blur_sigma: 1.0
    subsample_factor: 2 # 1 / subsample_factor
  # Load saved flows
  load: # Path to FOLDER with saved flows
  save: # Path to FOLDER where save homogs if empty no save
  debug: False

light_optim:
  use_tile: False
  tile_size: [2000,2000]

# Parameters regarding stitching
stitcher:
  mode: actual
  grid_size: 32
  optim_mode: ["scale"]
  optimizer: "LBFGS" # "adam" # LBFGS
  loss_type: "mse"
  lr: 0.1
  optim_steps: 50
  blend_width: 100
  flow_margin: 50
