# ----------------------
# docker-compose.oneshot.yml
# ----------------------
version: '3.8'

services:
  exposea:
    container_name: exposea
    build:
      context: .
      dockerfile: Dockerfile
    image: exposea:latest
    volumes:
      - ../test_data:/data  # !adjust!
      - ../output:/output  # !adjust!
    entrypoint: [ "/app/entrypoint-oneshot.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: no

  exposea_service:
    container_name: exposea_service
    build:
      context: .
      dockerfile: Dockerfile
    image: exposea:latest
    volumes:
      - ../test_data:/data  # !adjust!
      - ../output:/output  # !adjust!
    entrypoint: [ "/app/entrypoint-service.sh" ]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    restart: no
