debug: True # To output global debug values
exp_name: cave1 # Used for saving partial outputs

# Parameters regarding homography estimation
homog:
  type: default
  feature_extractor: SuperPoint # Method to extract features
  max_feat_points: 4096 # Maximum feature points to find
  feature_matcher: LightGlue # Method to match features
  do_optimization: False # Turn optimization on
  max_matches: 200 # Max points to match
  optimizer: marek # Type of optimization

  # Preload saved homographies
  load: #cache/homogs/opt_hom_20250512_092605.pkl
  save: #cache/homogs
  debug: False

# Parameters regarding optical flow estimation
optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960] # Size of input patches for model
  patch_overlap: [40,40] # Overlap of input patches
  subsample_factor: # [1,1] TODO Not working

  # Load saved flows
  load: flows_20250422_114408.pkl
  save: False
  debug: True

# Parameters regarding stitching
stitcher:
  mode: actual
  grid_size: 32
  optim_mode: ["scale"]
  optimizer: "LBFGS"
  loss_type: "mse"
  lr: 0.1
  optim_steps: 50
  num_iters: 50
  blend_width: 100

data:
  img_overview: 0.JPG
  img_folder: "imgs/example3"
  final_res: [6400, 8400]
