debug: True # To output global debug values
exp_name: david_big_map # Used for saving partial outputs

# Parameters regarding homography estimation
homog:
  type: default
  feature_extractor: SuperPoint # Method to extract features
  max_feat_points: 4096 # Maximum feature points to find
  feature_matcher: LightGlue # Method to match features
  do_optimization: False # Turn optimization on
  max_matches: 200 # Max points to match
  optimizer: marek # Type of optimization

  # Preload saved homographies
  load:
  save:
  debug: False

# Parameters regarding optical flow estimation
optical:
  model: ms_raft_p # sea_raft_m # memflow_t
  checkpoint: mixed # spring # sintel
  input_size: [840, 1260] # Y,X Size of input patches for model
  patch_overlap: [100,100] # Y,X Overlap of input patches
  subsample_factor: # [1,1] TODO Not working

  # Load saved flows
  load: # Path to FOLDER with saved flows
  save: # Path to FOLDER where save homogs if empty no save
  debug: False


# Parameters regarding stitching
stitcher:
  mode: actual
  grid_size: 32
  optim_mode: ["scale"]
  optimizer: "LBFGS"
  loss_type: "mse"
  lr: 0.1
  optim_steps: 50
  blend_width: 100

# Parameters regarding stitching
data:
  img_folder: "imgs/example_d" # Path to the images
  img_overview: 0.jpg # Name of overview image contained in img folder
  final_res: [14000, 18400] # Final resolution of image
