debug: True # To output global debug values

# Parameters regarding homography estimation
homog:
  type: default
  feature_extractor: SuperPoint
  max_feat_points: 4096
  feature_matcher: LightGlue
  do_optimization: False
  max_matches: 200 # Max points to match
  optimizer: marek # Type of optimization

  # Preload saved homographies
  load: #opt_hom_20250416_150301.pkl
  save: True
  debug: True

# Parameters regarding optical flow estimation
optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960] # Y,X Size of input patches for model
  patch_overlap: [40,40] # Y,X Overlap of input patches
  subsample_factor: # [1,1] TODO Not working

  # Load saved flows
  load: #flows_20250422_105423.pkl
  save: False
  debug: True

# Parameters regarding stitching
stitcher:
  mode: actual
  grid_size: 32
  optim_mode: ["scale"]
  optimizer: "LBFGS"
  loss_type: "mse"
  lr: 0.1
  optim_steps: 50
  num_iters: 50
  blend_width: 100

data:
  img_overview: 0.jpg
  img_folder: "imgs/example_d"
  img_pairs: [[0,1],[0,2],[0,3],[0,4],[0,5],[0,6],[0,7],[0,8],[0,9],
              [0,10], [0,11], [0,12], [0,13],[0,14], [0,15], [0,16],
              [0,17], [0,18], [0,19], [0,20],[0,21],[0,22],[0,23],[0,24],[0,25],[0,26],[0,27],[0,28],[0,29]]
  final_res: [6000, 7600] #[5956, 7535]
