debug: True # To output global debug values
exp_name: debug # Used for saving partial outputs


# Parameters regarding homography estimation
homog:
  type: default
  feature_extractor: SuperPoint # Method to extract features
  max_feat_points: 4096 # Maximum feature points to find
  feature_matcher: LightGlue # Method to match features
  do_optimization: False # Turn optimization on
  max_matches: 200 # Max points to match
  optimizer: marek # Type of optimization

  # Preload saved homographies
  load: #cache/homogs/opt_hom_20250512_092605.pkl
  save: #cache/homogs
  debug: True

# Parameters regarding optical flow estimation
optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960] # Size of input patches for model
  patch_overlap: [40,40] # Overlap of input patches
  # For image adjustment during calculation of optical flow
  adjust: False
  adjust_params:
    debug: True
    gaus_blur_sigma: 1.0
    subsample_factor: 0.5 # Double th

  # Load saved flows
  load: #cache/flows/debug/ # Path to FOLDER with saved flows
  save: # cache/flows/debug/ # Path to FOLDER where save homogs if empty no save
  debug: True

# Parameters for light optimization
light_optim:
  use_tile: True
  tile_size: [2000,2000]

# Parameters regarding stitching
stitcher:
  mode: actual
  grid_size: 32
  optim_mode: ["scale"]
  optimizer: "LBFGS"
  loss_type: "mse"
  lr: 0.1
  optim_steps: 50
  blend_width: 100

# Parameters regarding stitching
data:
  img_folder: "imgs/debug_example" # Path to the images
  img_overview: 0.JPG # Name of overview image contained in img folder
  process_res: [6000, 8000]
  final_res: [27000, 36000] # Final resolution of image

# Hydra exec dir to project dir
hydra:
  run:
    dir: .

