hydra:
  run:
    dir: .

debug: True
stitch_type: actual
homog:
  type: default
  feature_extractor: SuperPoint
  feature_matcher: LightGlue
  do_optimization: False
  max_matches: 200
  optimizer: marek
  debug: True
  load_homog: homog_debug.pkl


optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960]
  patch_overlap: [40,40]
  subsample_factor: # [1,1]
  load_flows: flows_debug.pkl

  # For debugging
  viz_patch: [13]

stitcher:
  blend_width: 100


data:
  img_overview: 0.JPG
  img_folder: "imgs/debug_example"
  img_pairs: [[0,1], [0,2], [0,3]]
  final_res: [6400, 8400]
