debug: True # To output global debug values
exp_name: debug # Used for saving partial outputs

# TOOD REMOVE
cache:
  is_on: True
  path: cache/diskcache/
  size_mb: 20000
# Parameters regarding homography estimation
homog:
  type: default
  feature_extractor: SuperPoint
  max_feat_points: 4096
  feature_matcher: LightGlue
  do_optimization: False
  max_matches: 200 # Max points to match
  optimizer: marek # Type of optimization

  # Preload saved homographies
  load: cache/homogs/opt_hom_20250507_190004.pkl #cache/homogs/ # Path to saved homographies pkl
  save: #cache/homogs/ # True
  debug: False

# Parameters regarding optical flow estimation
optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960] # Size of input patches for model
  patch_overlap: [40,40] # Overlap of input patches
  subsample_factor: # [1,1] TODO Not working

  # Load saved flows
  load: cache/flows/debug/ # Path to FOLDER with saved flows
  save: cache/flows/debug/ # Path to FOLDER where save homogs if empty no save
  debug: False

# Parameters regarding stitching
stitcher:
  mode: actual
  grid_size: 32
  optim_mode: ["scale"]
  optimizer: "LBFGS"
  loss_type: "mse"
  lr: 0.1
  optim_steps: 50
  blend_width: 100

  cache: False

# Parameters regarding stitching
data:
  img_overview: 0.JPG
  img_folder: "imgs/debug_example"
  img_pairs: [[0,1], [0,2], [0,3]]
  final_res: [6400, 8400]

# Hydra exec dir to project dir
hydra:
  run:
    dir: .

