hydra:
  run:
    dir: .

debug: True
stitch_type: actual
homog:
  type: default
  feature_extractor: SuperPoint
  feature_matcher: LightGlue
  do_optimization: False
  max_matches: 200
  optimizer: marek
  debug: True
  load_homog:


optical:
  model: sea_raft_m
  checkpoint: sintel
  input_size: [540, 960]
  patch_overlap: [10,10]
  subsample_factor: # [1,1]
  load_flows: #flows_20250303_132624.pkl

  # For debugging
  viz_patch: [13]


data:
  img_overview: 0.JPG
  img_folder: "imgs/example1"
<<<<<<< HEAD
  img_pairs: [[0,1],[0,2],[0,3],[0,4],[0,5],[0,6],[0,7]]
=======
  img_pairs: [[0,1],[0,2],[0,3],[0,4],[0,5],[0,6],[0,7],[1,2],[1,3], [2,4], [3,5], [4,6], [2,7]]
>>>>>>> 9bbc8bc (Initial commit)
  final_res: [6400, 8400]
