hydra:
  run:
    dir: .

debug: True
stitch_type: actual
homog:
  type: default
  feature_extractor: SuperPoint
  feature_matcher: LightGlue
  do_optimization: False
  max_matches: 200
  optimizer: marek
  debug: True
  load_homog:


optical:
  model: sea_raft_m
  checkpoint: sintel
  input_size: [540, 960]
  patch_overlap: [10,10]
  subsample_factor: # [1,1]
  load_flows: #flows_20250303_132624.pkl

  # For debugging
  viz_patch: [13]


data:
  img_overview: 0.JPG
  img_folder: "imgs/debug_example"
  img_pairs: [[0,1]]
  final_res: [6400, 8400]
