# Required parameters

exp_name: cave_1          # Used for saving partial outputs if not specified random string is generated
img_overview: 0.JPG       # Name of overview image contained in input folder
preset_name: p_normal     # Preset to be used, if not specified p_normal is used

# Optional override parameters. All preset parameters can be customized and override here
# Check presets to see the structure of parameters

