debug: True # To output global debug values
exp_name: map1 # Used for saving partial output

cache:
  is_on: True
  path: cache/diskcache/
  size_mb: 20000

# Parameters regarding homography estimation
homog:
  type: default
  feature_extractor: SuperPoint
  max_feat_points: 4096
  feature_matcher: LightGlue
  do_optimization: False
  max_matches: 200 # Max points to match
  optimizer: marek # Type of optimization

  # Preload saved homographies
  load: #cache/homogs/opt_hom_20250512_092605.pkl
  save: #cache/homogs
  debug: False

# Parameters regarding optical flow estimation
optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960] # Size of input patches for model
  patch_overlap: [40,40] # Overlap of input patches
  # For image adjustment during calculation of optical flow
  adjust: True
  adjust_params:
    debug: True
    gaus_blur_sigma: 1.0
    subsample_factor: 0.5 # Double th

  # Load saved flows
  load: #cache/flows # Path to flow
  save: #cache/flows
  debug: False

# Parameters for light optimization
light_optim:
  use_tile: False
  tile_size: [2000,2000]


# Parameters regarding stitching
stitcher:
  mode: actual
  grid_size: 32
  optim_mode: ["scale"]
  optimizer: "LBFGS"
  loss_type: "mse"
  lr: 0.1
  optim_steps: 50
  blend_width: 100


data:
  img_overview: 0.JPG
  img_folder: "imgs/example1"
  img_pairs: [[0,1],[0,2],[0,3],[0,4],[0,5],[0,6],[0,7]]
  final_res: [6400, 8400] # Final resolution of output

# Hydra exec dir to project dir
hydra:
  run:
    dir: .

