# By default hydra changes working dir, this PREVENTS that
hydra:
  run:
    dir: .

debug: True
stitch_type: actual

homog:
  type: default
  feature_extractor: SuperPoint
  feature_matcher: LightGlue
  do_optimization: False
  max_kpts: 4096
  max_matches: 200
  optimizer: marek
  debug: True
  load_homog: opt_hom_20250319_125853.pkl

optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960]
  patch_overlap: [20,20]
  subsample_factor: # [1,1]
  load_flows: flows_20250322_233659.pkl
  # For debugging
  viz_patch: [13]


data:
  img_overview: 0.JPG
  img_folder: "imgs/example1"
  img_pairs: [[0,1],[0,2],[0,3],[0,4],[0,5],[0,6],[0,7]]
  final_res: [6400, 8400]
