debug: True # To output global debug values

# Parameters regarding homography estimation
homog:
  type: default
  feature_extractor: SuperPoint
  feature_matcher: LightGlue
  do_optimization: False
  max_matches: 200 # Max points to match
  optimizer: marek # Type of optimization

  # Preload saved homographies
  load: # Path to homog
  save: True
  debug: True

# Parameters regarding optical flow estimation
optical:
  model: memflow_t
  checkpoint: sintel
  input_size: [540, 960] # Size of input patches for model
  patch_overlap: [40,40] # Overlap of input patches
  subsample_factor: # [1,1] TODO Not working

  # Load saved flows
  load: # Path to flow
  save: True
  debug: True

# Parameters regarding stitching
stitcher:
  mode: actual
  blend_width: 100


data:
  img_overview: 0.JPG
  img_folder: "imgs/example1"
  img_pairs: [[0,1],[0,2],[0,3],[0,4],[0,5],[0,6],[0,7]]
  final_res: [6400, 8400]

# Hydra exec dir to project dir
hydra:
  run:
    dir: .

